[phases.setup]
cmds = ["curl -fsSL https://deb.nodesource.com/setup_20.x | bash -"]

[phases.install]
cmds = ["apt-get install -y nodejs"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve dist/portafolio/browser -s"
